site_name: Docs as Code
site_description: Documentation CI/CD pipeline
site_author: Gaurav Sharma

theme:
  name: material

nav:
  - Home: index.md
  - Design: design.md
  - Architecture: architecture.md

